#include "include/predict.h"
#include "include/dml_operators.h"

int predict(SubTARIndex subtarIndex, OperationPtr operation,
            ConfigurationManagerPtr configurationManager,
            QueryDataManagerPtr queryDataManager,
            MetadataManagerPtr metadataManager, StorageManagerPtr storageManager,
            EnginePtr engine) {

  TARGeneratorPtr generator, outputGenerator;

  //input TAR is a parameter in the operation
  TARPtr inputTAR = operation->GetParametersByName("operand0")->tar;

  //output TAR is generated by the current operator
  TARPtr outputTAR = operation->GetResultingTAR();

  //Setting generators for the input and output TAR
  SET_GENERATOR(generator, inputTAR->GetName());
  SET_GENERATOR(outputGenerator, outputTAR->GetName());

  //Getting current subTAR
  auto subtar = generator->GetSubtar(subtarIndex);

  //If subtar is null, return
  if(subtar == nullptr){
    return SAVIME_SUCCESS;
  }

  //Create new subtar
  SubtarPtr newSubtar = make_shared<Subtar>();
  generator->TestAndDisposeSubtar(subtarIndex);

  //Iterating over the datasets for the attributes
  for (auto entry : subtar->GetDataSets()) {
    if (outputTAR->GetDataElement(entry.first) != nullptr){
      /*Here you should make the subtar's dataset equals to 0.*/
      /*Before adding a new subTAR.*/
      newSubtar->AddDataSet(entry.first, entry.second);
    }
  }

  //Iterating over the dimension specifications of the dataset
  for (auto entry : subtar->GetDimSpecs()) {
    newSubtar->AddDimensionsSpecification(entry.second);
  }

  //Setting output subTAR equal to the input subTAR
  outputGenerator->AddSubtar(subtarIndex, newSubtar);

  //Must return success
  return SAVIME_SUCCESS;
}
